# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy to server

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v3
    #切换分支
    - name: checkout
      uses: actions/checkout@master
      with: 
        submodules: recursive

    - name: Install Dependencies
      run : yarn 

    - name : Build
      run : yarn build

    # Deploy
    - name: Deploy
      uses: easingthemes/ssh-deploy@v2.2.11
      with:
        SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
        SOURCE: "docs/.vuepress/dist/"
        REMOTE_HOST: "101.35.18.131"
        REMOTE_USER: "ubuntu"
        ARGS: "-rltgoDzvO --delete"
        TARGET: "/var/www/html/"
    

