# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy to server

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v3
    #切换分支
    - name: checkout
      uses: actions/checkout@master
    
    # 更新子模块
    - name: submodules-init
      # You may pin to the exact commit or the version.
      # uses: snickerbockers/submodules-init@74927a8bb0fe1bb0f1f1e4d102384a8e69f19171
      uses: snickerbockers/submodules-init@v4

    - name: Install Dependencies
      run : yarn 

    - name : Build
      run : yarn build
