# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy to server

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v3
    #切换分支
    - name: checkout
      uses: actions/checkout@master
      with: 
        submodules: recursive

    - name: Install Dependencies
      run : yarn 

    - name : Build
      run : yarn build
    
    # 部署
    - name : deploy
      uses : easingthemes/ssh-deploy@v2.2.11
      with : 
        # Private Key
        SSH_PRIVATE_KEY : ${{ secrets.ACCESS_TOKEN }}
        # Remote host
        REMOTE_HOST : ${{ secrets.HOST }} 
        # Remote user
        REMOTE_USER : ${{ secrets.USER }} 
        # Source directory
        SOURCE : "dist/"
        # Target directory
        TARGET : "/var/www/html/"
